version: "3.8"
services:
  mysql8:
    image: mysql:8.0.31
    restart: always
    volumes:
      - "./.docker/mysql/volume:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "${MYSQL_DB_NAME:?err}"
      MYSQL_USER: "${MYSQL_USER_NAME:?err}"
      MYSQL_PASSWORD: "${MYSQL_USER_PSWD:?err}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PSWD:?err}"
    ports:
      - "${MYSQL_PORT:?err}:3306"

  rabbitmq:
    image: rabbitmq:3.11.3-management
    ports:
      - 5672:5672
      - 15672:15672
